### ISSUE TITLE
Installation instructions for Fedora: Bad practice

### ISSUE THREAD

**Issue by akahl-lshift** [aiven/kafkajournalpump#11]
I don't know about whether this is a normal thing to do in Debian land, but in Fedora and derivatives, there's one general rule towards using `rpm` as a low-level tool for managing packages: Don't.
tl;dr: Instruct users to run `su -c 'dnf install --nogpgcheck ...'` for recent versions of Fedora, `su -c 'yum install --nogpgcheck ...'` for older versions including recent RHEL and CentOS.

Reasons: dnf and yum wrap RPM operations in safe transactions and also log them to a special transaction log which can be inspected and operated upon, including rollbacks.
Please don't punish Fedora users for features Debian doesn't provide.

**Comment by Ormod** [comment]
Can you please submit a PR to fix the documentation.
